/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\backpack.gltf 
Author: kam (https://sketchfab.com/menhankam)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/hiking-backpack-ffd0bd8f61034f17a90e41fe8f2da003
Title: Hiking Backpack
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

export function Backpack(props) {
  const { nodes, materials } = useGLTF('/backpack/backpack.gltf')
  return (
    <Center {...props}>
    <group {...props} dispose={null}>
      <group position={[0, -2 , 0]} scale={0.04}>
        <mesh geometry={nodes['body_l001_Material_#1001_0'].geometry} material={materials.Material_1001} />
        <mesh geometry={nodes['atas_l001_Material_#1001_0'].geometry} material={materials.Material_1001} />
        <mesh geometry={nodes['back_l001_Material_#1001_0'].geometry} material={materials.Material_1001} />
        <mesh geometry={nodes['clip017_Material_#999_0'].geometry} material={materials.Material_999} position={[18.1, 83.435, -5.739]} rotation={[-Math.PI / 2, 1.425, 1.597]} scale={0.136} />
        <mesh geometry={nodes['clip018_Material_#999_0'].geometry} material={materials.Material_999} position={[18.1, 83.435, -5.739]} rotation={[-Math.PI / 2, 1.425, 1.597]} scale={0.136} />
        <mesh geometry={nodes['clip019_Material_#1003_0'].geometry} material={materials.Material_1003} position={[18.1, 83.435, -5.739]} rotation={[-Math.PI / 2, 1.425, 1.597]} scale={0.136} />
        <mesh geometry={nodes['clip020_Material_#1003_0'].geometry} material={materials.Material_1003} position={[18.167, 82.856, -5.754]} rotation={[-Math.PI / 2, 1.425, -1.544]} scale={0.136} />
        <mesh geometry={nodes['clip021_Material_#999_0'].geometry} material={materials.Material_999} position={[13.457, 75.522, -21.917]} rotation={[-2.98, 0.975, 3.058]} scale={0.141} />
        <mesh geometry={nodes['clip022_Material_#999_0'].geometry} material={materials.Material_999} position={[13.457, 75.522, -21.917]} rotation={[-2.98, 0.975, 3.058]} scale={0.141} />
        <mesh geometry={nodes['clip023_Material_#1003_0'].geometry} material={materials.Material_1003} position={[13.457, 75.522, -21.917]} rotation={[-2.98, 0.975, 3.058]} scale={0.141} />
        <mesh geometry={nodes['clip024_Material_#1003_0'].geometry} material={materials.Material_1003} position={[13.469, 74.92, -21.962]} rotation={[-2.98, 0.975, -0.083]} scale={0.141} />
        <mesh geometry={nodes['clip025_Material_#999_0'].geometry} material={materials.Material_999} position={[13.24, 76.986, 10.308]} rotation={[-0.253, 1.029, 0.217]} scale={0.137} />
        <mesh geometry={nodes['clip026_Material_#999_0'].geometry} material={materials.Material_999} position={[13.24, 76.986, 10.308]} rotation={[-0.253, 1.029, 0.217]} scale={0.137} />
        <mesh geometry={nodes['clip027_Material_#1003_0'].geometry} material={materials.Material_1003} position={[13.24, 76.986, 10.308]} rotation={[-0.253, 1.029, 0.217]} scale={0.137} />
        <mesh geometry={nodes['clip028_Material_#1003_0'].geometry} material={materials.Material_1003} position={[13.289, 76.402, 10.337]} rotation={[-0.253, 1.029, -2.925]} scale={0.137} />
        <mesh geometry={nodes['clipu015_Material_#999_0'].geometry} material={materials.Material_999} position={[-6.127, 19.284, 8.341]} rotation={[0.501, -0.811, -0.403]} scale={5.995} />
        <mesh geometry={nodes['clipu016_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-5.72, 22.112, 12.431]} rotation={[0.285, -0.73, 2.588]} scale={0.152} />
        <mesh geometry={nodes['clipu017_Material_#999_0'].geometry} material={materials.Material_999} position={[-3.016, 76.526, 12.285]} rotation={[-0.347, -0.772, 0.592]} scale={5.995} />
        <mesh geometry={nodes['clipu018_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-5.816, 79.96, 9.989]} rotation={[-0.569, -0.858, -2.711]} scale={0.152} />
        <mesh geometry={nodes['clipu019_Material_#999_0'].geometry} material={materials.Material_999} position={[-4.256, 78.109, -22.125]} rotation={[-2.892, -0.668, -0.714]} scale={5.995} />
        <mesh geometry={nodes['clipu020_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-2.539, 75.294, -25.87]} rotation={[-3.046, -0.547, 2.339]} scale={0.152} />
        <mesh geometry={nodes['clipu021_Material_#999_0'].geometry} material={materials.Material_999} position={[-5.265, 21.112, -22.934]} rotation={[2.651, -0.885, 0.493]} scale={5.995} />
        <mesh geometry={nodes['clipu022_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-7.673, 17.821, -20.059]} rotation={[2.384, -0.952, -2.861]} scale={0.152} />
        <mesh geometry={nodes['clipu023_Material_#999_0'].geometry} material={materials.Material_999} position={[-12.173, 27.393, 6.841]} rotation={[0.143, -0.198, 0.448]} scale={5.995} />
        <mesh geometry={nodes['clipu024_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-14.468, 31.591, 8.26]} rotation={[-0.02, -0.271, -2.732]} scale={0.152} />
        <mesh geometry={nodes['clipu025_Material_#999_0'].geometry} material={materials.Material_999} position={[-12.395, 27.02, -18.855]} rotation={[3.109, -0.172, 2.696]} scale={5.995} />
        <mesh geometry={nodes['clipu026_Material_#1003_0'].geometry} material={materials.Material_1003} position={[-14.659, 31.351, -19.862]} rotation={[-3.012, -0.245, -0.412]} scale={0.152} />
        <mesh geometry={nodes['depan_l001_Material_#1001_0'].geometry} material={materials.Material_1001} />
        <mesh geometry={nodes['pipe_l001_Material_#1004_0'].geometry} material={materials.Material_1004} />
        <mesh geometry={nodes['strap_l001_Material_#1001_0'].geometry} material={materials.Material_1001} />
        <mesh geometry={nodes['zio_l001_Material_#1000_0'].geometry} material={materials.Material_1000} />
        <mesh geometry={nodes['zio_l001_Material_#1004_0'].geometry} material={materials.Material_1004} />
      </group>
    </group>
    </Center>
  )
}

useGLTF.preload('/backpack/backpack.gltf')
