/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\boots.gltf 
Author: EFX (https://sketchfab.com/evan4129)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hiking-boots-lowpoly-1f25fa279bdc4f87b1374566e9e62923
Title: Hiking Boots LOWPOLY
*/

import React from 'react'
import { useGLTF, Center  } from '@react-three/drei'

export function Boots(props) {
  const { nodes, materials } = useGLTF('/boots/boots.gltf')
  return (
    <Center {...props}>
    <group {...props} dispose={null} scale={3}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.HikiingBoot} rotation={[-1.487, 0, 0]} />
    </group>
    </Center>
  )
}

useGLTF.preload('/boots/boots.gltf')
